---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boutique-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boutique-store
  template:
    metadata:
      labels:
        app: boutique-store
    spec:
      containers:
      - name: boutique-store
        image: sholly333/boutique-store:latest
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: boutique-store-service
spec:
  selector:
    app: boutique-store
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
